# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: NeSy 2025 Conference
email: organisers@nesyconf.org
description: >- # this means to ignore newlines until "baseurl:"
  NeSy AI is the association for neurosymbolic Artificial Intelligence. It runs NeSy, the premier international conference on neural-symbolic learning and reasoning, yearly since 2005, with a focus on neuro-symbolic systems, machine learning and reasoning in deep learning, knowledge graphs and generative AI, hybrid systems and applications of AI including in healthcare, finance, business, mathematics, manufacturing, retail, logistics, science and engineering. NeSy special areas of interest include network verification and safety, AI accountability and risks, explainable AI, knowledge extraction, ontology learning, multimodal learning, reasoning in large language models, computer vision and applications in computer science, including databases, human-machine interaction, natural language processing, software engineering and formal methods, robotics and control systems. This site hosts the NeSy 2025 conference, which is the 19th edition of the international conference on neurosymbolic learning and reasoning.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://2025.nesyconf.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nesyconf
github_username: nesyconf
author: "Neurosymbolic Learning and Reasoning Association"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- index.md
# - speakers.md
- organizers.md
- callforpapers.md
- travel_information.md
- registration.md
- schedule.md
# - papers.md
# - contactus.md

# # Specify the name of a file to show as a masthead graphic at the top of each page, instead of a title, here:
# masthead: assets/img/banner.jpg
# # Description (alt text) for the masthead
# masthead_description: Adapted from Machine Learning & Artificial Intelligence by mikemacmarketing; licensed under CC BY 2.0

# A two-line attribution (remove this if you have to, but we'd appreciate if you leave this as is)
#Based on a <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> template from a <a href="https://krrish94.github.io">lazy grad student</a>.
#  Some icons made by <a href="https://smashicons.com/" title="Smashicons">Smashicons</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a>.
attribution: 
  

# Displays a "last updated" date in the footer if set to "true"
last_updated: false

# Define collections (speakers, organizers, papers)
# To turn off any of these collections, just set "output" to "false"
collections:
  speakers:
    output: true
  organizers:
    output: true
  schedule:
    sort_by: sequence_id
    output: true
  papers:
    sort_by: sequence_id
    output: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Google analytics id. Add your tracking id to get visitor stats.
# google_analytics: # tracking id
